server:
  port: 8500 # API ??? ??? ?? ?? (???)
  servlet:
    context-path: /api # ?? API ????? ?? ?? ?? ?? ?? (?: /api/bookings)
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL ???? (???? DB? ?? ?????)
    url: jdbc:mysql://localhost:3306/reservation
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
logging:
  level:
    # SQL ?? ????(PreparedStatement)? ??? ???? ?? ? ??
    org.hibernate.SQL: DEBUG
    org.springframework.web: INFO